### ISSUE TITLE
Compile error because of Utils.hpp

### ISSUE THREAD

**Issue by junfenglx** [hassyGo/SVOembedding#1]
Hello:

When I compile the code, I encounter a error of `isnan` and `isinf` not declare in `Utils.hpp`.

Here is the patch I changed to make the code compiled successfully.

[fix_isnan_error.patch.txt](https://github.com/hassyGo/SVOembedding/files/432332/fix_isnan_error.patch.txt)

By the way, do you have the plan to release the code of the paper
**Adaptive Joint Learning of Compositional and Non-Compositional Phrase Embeddings**

Thanks!

**Comment by hassyGo** [comment]
Thanks!
I'm now very busy in visiting US, but I will fix the issue later!
